<a href="https://colab.research.google.com/github/fairymetal/bootcamp-data-science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Hello')

Hello


In [2]:
import numpy as np
np.random.seed(0)
np.random.rand(10)
np.random.choice(['p', 'b', 'a', '7', 'end', 'sl'])

'p'

In [ ]:
np.all([2,5, 3, 8, 0])


False

In [ ]:
np.any([2,0, 0, 0, 0])

True

In [ ]:
A = np.arange(start=-10, stop =10, step = 0.5)
A = A.reshape(10,-1)
A


array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
A.T

array([[-10. ,  -8. ,  -6. ,  -4. ,  -2. ,   0. ,   2. ,   4. ,   6. ,
          8. ],
       [ -9.5,  -7.5,  -5.5,  -3.5,  -1.5,   0.5,   2.5,   4.5,   6.5,
          8.5],
       [ -9. ,  -7. ,  -5. ,  -3. ,  -1. ,   1. ,   3. ,   5. ,   7. ,
          9. ],
       [ -8.5,  -6.5,  -4.5,  -2.5,  -0.5,   1.5,   3.5,   5.5,   7.5,
          9.5]])

In [ ]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.bitwise_and(A>-5, A<5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
A[np.bitwise_and(A>-5, A<5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [ ]:
A[np.bitwise_or(A<-5, A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])

In [4]:
# rozwiązywanie układów równań metodą macierzową

# 2x + 4y = 10, x-y = -1


A = np.array([[2, 4],[1,-1]])
print(A)
B = np.array([[10],[-1]])
print(B)

# MACIERZ ODWÓCONA:    A_inv*A = A*A_inv = macierz jednostkowa
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print(A_inv)
print(X) # - wynik

[[ 2  4]
 [ 1 -1]]
[[10]
 [-1]]
[[ 0.16666667  0.66666667]
 [ 0.16666667 -0.33333333]]
[[1.]
 [2.]]


In [6]:
# statystyka 
price = np.array([[12.4, 13.0, 20.9, 100],
                  [12.8, 13.5, 20.5, 300],
                  [12.1, 13.8, 20.4, 500]])

price.sum()

1039.4

In [7]:
price.sum(axis=0) # po kolumnach 

array([ 37.3,  40.3,  61.8, 900. ])

In [8]:
price.sum(axis=1) # po wierszach

array([146.3, 346.8, 546.3])

In [10]:
np.min(price, axis=1)

array([12.4, 12.8, 12.1])

In [11]:
np.median(price)

17.1

In [12]:
np.mean(price,axis = 0)

array([ 12.43333333,  13.43333333,  20.6       , 300.        ])